export type PhysicsVisualFamily =
  | 'motion'
  | 'ac-wave'
  | 'lc-oscillation'
  | 'heat-engine'
  | 'experiment-fit'
  | 'transformer'
  | 'sensor'
  | 'pv-process'
  | 'nuclear'
  | 'projectile'
  | 'force'
  | 'orbit'
  | 'energy'
  | 'momentum'
  | 'oscillation'
  | 'wave'
  | 'optics'
  | 'electrostatic'
  | 'electric'
  | 'magnet'
  | 'thermal'
  | 'induction'
  | 'modern'

export type ChemistryVisualFamily =
  | 'stoich'
  | 'separation'
  | 'quantitative-error'
  | 'electrolysis-corrosion'
  | 'titration'
  | 'apparatus'
  | 'organic-reaction'
  | 'ions'
  | 'redox'
  | 'periodic'
  | 'thermochemistry'
  | 'rate'
  | 'equilibrium'
  | 'acid'
  | 'precipitation'
  | 'electrochem'
  | 'structure'
  | 'crystal'
  | 'inorganic'
  | 'organic'
  | 'spectrum'
  | 'materials'
  | 'experiment'

function classifyPhysics(text: string): PhysicsVisualFamily | undefined {
  if (/功率和动量的前置联系/.test(text)) return 'energy'
  if (/图像拟合|实验拟合|误差传播|a[—-]F|a[—-]1\/m|线性化|有效数字|实验不确定度/.test(text)) return 'experiment-fit'
  if (/热机|卡诺|热机效率|能源品质/.test(text)) return 'heat-engine'
  if (/电磁振荡|LC振荡|电磁波|无线电波|振荡电路/.test(text)) return 'lc-oscillation'
  if (/交变电流|正弦式|峰值|有效值|感抗|容抗/.test(text)) return 'ac-wave'
  if (/变压器|匝数比|升压|降压|远距离输电|输电损耗/.test(text)) return 'transformer'
  if (/传感器|敏感元件|输入与输出|自动控制|反馈/.test(text)) return 'sensor'
  if (/p[-—–]?V|气体做功|等温等压等容|等温过程|等压过程|等容过程|气体状态变化与图像/.test(text)) return 'pv-process'
  if (/原子核|核反应|衰变|半衰期|裂变|聚变|质量亏损|结合能|辐射/.test(text)) return 'nuclear'
  if (/电磁感应|交变电流|变压器|输电|电能输送|自感|互感|涡流|楞次|法拉第/.test(text)) return 'induction'
  if (/光电|光量子|原子|原子核|核物理|能级|衰变|裂变|聚变|辐射|波粒二象性/.test(text)) return 'modern'
  if (/几何光学|成像|反射|折射|透镜/.test(text)) return 'optics'
  if (/磁场|磁感|磁通线|洛伦兹|安培力|质谱|霍尔|速度选择器|回旋|带电粒子.*圆周/.test(text)) return 'magnet'
  if (/电路|欧姆|电流|电功率|电功|焦耳热|电压|电阻|电源|内阻|伏安|电表|串联|并联|含源/.test(text)) return 'electric'
  if (/静电|电荷|库仑|电场|电势|等势|电容|带电粒子偏转|带电粒子在电场/.test(text)) return 'electrostatic'
  if (/功的|恒力功|变力功|功与|势能|动能|机械能|功能关系|摩擦生热|能量守恒|能源|能量品质/.test(text)) return 'energy'
  if (/热|气体|分子动理论|扩散|温度|内能/.test(text)) return 'thermal'
  if (/机械振动|简谐|弹簧振子|单摆|振动图像|回复力|受迫振动|共振|阻尼/.test(text)) return 'oscillation'
  if (/机械波|横波|纵波|介质质点|波长|波速|波的图像|波形|波的叠加|干涉|衍射|偏振|多普勒|波动光学|光的波动性/.test(text)) return 'wave'
  if (/动量|冲量|反冲|火箭|爆炸|碰撞/.test(text)) return 'momentum'
  if (/曲线运动|平抛|斜抛|渡河|关联速度|运动的合成|运动的分解/.test(text)) return 'projectile'
  if (/圆周|向心|万有引力|开普勒|宇宙速度|卫星|航天|同步|变轨|轨道/.test(text)) return 'orbit'
  if (/受力|牛顿|重力|重心|弹力|胡克|摩擦|力的合成|力的分解|共点力|超重|失重|连接体|斜面|传送带|临界/.test(text)) return 'force'
  if (/速度|加速度|匀变速|自由落体|运动图像|追及|相遇|位移|路程|参考系|质点|测量/.test(text)) return 'motion'
  return undefined
}

function classifyChemistry(text: string): ChemistryVisualFamily | undefined {
  if (/单质.*氧化物.*酸碱盐|物质类别|纯净物|混合物|树状分类|交叉分类|化合.*分解.*置换.*复分解|分类标准/.test(text)) return 'ions'
  if (/有机物分离提纯|物质分离提纯与检验|分离提纯与检验|过滤|蒸馏|萃取|分液|重结晶|色谱/.test(text)) return 'separation'
  if (/定量实验|实验条件控制|变量设计|误差分析|有效数字|平行实验|实验方案评价/.test(text)) return 'quantitative-error'
  if (/电解池|电解规律|电解法|电镀|腐蚀|牺牲阳极|外加电流.*保护/.test(text)) return 'electrolysis-corrosion'
  if (/中和滴定|酸碱滴定|滴定曲线|等量点|滴定终点|指示剂.*变色/.test(text)) return 'titration'
  if (/气体制备|制备.*净化.*收集|发生装置|收集方法|排水集气|排空气|防倒吸|尾气处理/.test(text)) return 'apparatus'
  if (/有机.*反应|烷烃.*取代|烯烃|炔烃|卤代烃|醇.*氧化|醛.*氧化|羧酸.*酯|酯化|酯.*水解|官能团.*转化|加成反应|取代反应|消去反应/.test(text)) return 'organic-reaction'
  if (/电化学|原电池|电解池|电解规律|电解法|电镀|腐蚀|电极|电池|盐桥|电子流向|正极|负极|阴极|阳极/.test(text)) return 'electrochem'
  if (/沉淀|溶度积|Ksp/.test(text)) return 'precipitation'
  if (/氧化数|氧化剂|还原剂|电子转移|电子守恒|氧化还原|价态变化|价态转化/.test(text)) return 'redox'
  if (/反应热|焓变|热化学|吸热|放热|盖斯|燃烧热|热量|总能量|能量图|活化能|键能/.test(text)) return 'thermochemistry'
  if (/反应速率|速率方程|有效碰撞|催化剂|浓度.*速率|温度.*速率/.test(text)) return 'rate'
  if (/化学平衡|动态平衡|平衡常数|平衡移动|可逆反应|反应限度|反应原理综合|综合平衡图像/.test(text)) return 'equilibrium'
  if (/酸碱|酸性|碱性|弱电解质|电离平衡|离子积|pH|滴定|盐类水解|质子/.test(text)) return 'acid'
  if (/原子结构|元素位置|周期表|周期律|周期变化|周期推断|金属性|非金属性|电离能|电负性|微粒半径|核外电子|电子排布|原子轨道|能层|能级/.test(text)) return 'periodic'
  if (/离子反应|离子方程式|电解质|电离|离子共存|胶体|分散系|物质分类|物质的分类/.test(text)) return 'ions'
  if (/晶胞|晶体|非晶体|堆积|晶格|晶体缺陷/.test(text)) return 'crystal'
  if (/质谱|红外|核磁|波谱|结构信息|谱图证据|有机物分离|分离提纯/.test(text)) return 'spectrum'
  if (/有机|烷|烯|炔|苯|醇|酚|醚|醛|酮|羧酸|酯|官能团|高分子|同分异构|碳链|碳骨架|糖类|油脂|蛋白质/.test(text)) return 'organic'
  if (/氯气|氯水|卤素|硫酸|硫及|氮气|氮氧化物|氨|铵盐|硝酸|含氮|无机|元素转化|氯硫氮/.test(text)) return 'inorganic'
  if (/钠|镁|铝|铁|铜|金属|合金|冶炼|材料|资源|煤|石油|天然气|污染|绿色化学|原子经济|生命周期|循环化学/.test(text)) return 'materials'
  if (/结构|共价键|离子键|化学键|杂化|分子构型|分子空间|价层电子对|分子极性|氢键|分子间作用力/.test(text)) return 'structure'
  if (/实验|制备|净化|收集|检验|流程|分离|安全|误差|变量|方案|现象|证据/.test(text)) return 'experiment'
  if (/物质的量|阿伏加德罗|摩尔|粒子数|浓度|气体体积|化学计量|守恒|计算/.test(text)) return 'stoich'
  return undefined
}

export function resolvePhysicsVisualFamily(topicTitle: string, unitTitle: string): PhysicsVisualFamily {
  return classifyPhysics(topicTitle) ?? classifyPhysics(unitTitle) ?? 'motion'
}

export function resolveChemistryVisualFamily(topicTitle: string, unitTitle: string): ChemistryVisualFamily {
  return classifyChemistry(topicTitle) ?? classifyChemistry(unitTitle) ?? 'stoich'
}
